### ISSUE TITLE
Optional future to-do's

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/pronamic-pay-ideal-2#1]
- [ ] Add support for `CreateTransactionRequest.transactionCallbackUrl`.
- [ ] Simplify certificate configuration.
- [x] Improve unhappy path error handling.
- [x] #2
